Feature/2012 fieldlines
OpenSpace/OpenSpace pull request #2042
Opened 2022-04-22 21:19 UTC by ElonOlsson

Adding assets for another solar storm event, July 2012.
Some changes to renderable and adjustments to other assets were made, + general clean up

2022-04-26 11:32 UTC, alexanderbock commented on data/assets/scene/solarsystem/heliosphere/2012/sun_earth_2012_fieldlines.asset
> +-- local sceneHelper = asset.require('util/scene_helper')
Can probably remove all of the comments here that are no longer necessary

2022-04-26 11:32 UTC, alexanderbock commented on data/assets/scene/solarsystem/heliosphere/2012/sun_earth_2012_fieldlines_batsrus.asset
> +local batsrusTemperatureColorTable = transferFunctions .. "/batsrus_temperature.txt"
The beginning `/` is no longer necessary;  it was before

2022-04-26 11:32 UTC, alexanderbock commented on data/assets/scene/solarsystem/heliosphere/2012/sun_earth_2012_fieldlines_batsrus.asset
> +BATSRUSPaths = {
This variable should be declared as `local`

2022-04-26 11:32 UTC, alexanderbock commented on data/assets/scene/solarsystem/heliosphere/2012/sun_earth_2012_fieldlines_batsrus.asset
> +    ColorQuantity = 0, -- Temprature
-> Temperature

2022-04-26 11:32 UTC, alexanderbock commented on data/assets/scene/solarsystem/heliosphere/2012/sun_earth_2012_fieldlines_batsrus.asset
> +    --[[ ExtraMinMaxLimits = {
Are the comments still reasonable?  Otherwise they should go as well

2022-04-26 11:32 UTC, alexanderbock commented on data/assets/scene/solarsystem/heliosphere/2012/sun_earth_2012_fieldlines_batsrus.asset
> +    --[[ ExtraMinMaxLimits = {
Same here

2022-04-26 11:32 UTC, alexanderbock commented on data/assets/scene/solarsystem/heliosphere/2012/sun_earth_2012_fieldlines_batsrus.asset
> +    --[[ ExtraMinMaxLimits = {
And here

2022-04-26 11:32 UTC, alexanderbock commented on data/assets/scene/solarsystem/heliosphere/2012/sun_earth_2012_fieldlines_batsrus.asset
> +  -- openspace.setPropertyValueSingle("Scene.FL_BATSRUS_J12_OpenClosed.Renderable.Color.colorMethod", 1) -- Color by Quantity
And here

2022-04-26 11:32 UTC, alexanderbock commented on data/assets/scene/solarsystem/heliosphere/2012/sun_earth_2012_fieldlines_batsrus.asset
> +  openspace.removeSceneGraphNode(BatsrusJ12OpenClosed)
It's usually a good idea to have the scene graph nodes in reverse order here from the onInitialize.  That way we won't get any weird behavior if nodes depend on each other. So:
```lua
openspace.removeSceneGraphNode(BatsrusAsherStaticSeedsFlowLines)
openspace.removeSceneGraphNode(BatsrusJ12FlowLines)
openspace.removeSceneGraphNode(BatsrusJ12OpenClosed)
```

2022-04-26 11:32 UTC, alexanderbock commented on data/assets/scene/solarsystem/heliosphere/2012/sun_earth_2012_fieldlines_enlil.asset
> +-- Specifying transfer functions
This comment seems wrong?

2022-04-26 11:32 UTC, alexanderbock commented on data/assets/scene/solarsystem/heliosphere/2012/sun_earth_2012_fieldlines_enlil.asset
> +local enlilDensityColorTable = transferFunctions .. "/enlil_density.txt"
Same comment as above;  the `/` is not necessary anymore

2022-04-26 11:32 UTC, alexanderbock commented on data/assets/scene/solarsystem/heliosphere/2012/sun_earth_2012_fieldlines_enlil.asset
> +    --ExtraMinMaxLimits = {
Check for unused commented out parts

2022-04-26 11:32 UTC, alexanderbock commented on data/assets/scene/solarsystem/heliosphere/2012/sun_earth_2012_fieldlines_pfss.asset
> +-- Specifying transfer functions
Comment seems to be a copy-and-paste error

2022-04-26 11:32 UTC, alexanderbock commented on data/assets/scene/solarsystem/heliosphere/2012/sun_earth_2012_fieldlines_enlil.asset
> +  openspace.removeSceneGraphNode(ENLILSliceEqPlane11AU1)
See comment above about reversing the order here

2022-04-26 11:32 UTC, alexanderbock commented on data/assets/scene/solarsystem/heliosphere/2012/sun_earth_2012_fieldlines_pfss.asset
> +local pfssTransitionColorTable = transferFunctions .. "/pfss_transition.txt";
Lua doesn't require the `;` at the end of the lines and they can go

2022-04-26 11:32 UTC, alexanderbock commented on data/assets/scene/solarsystem/heliosphere/2012/sun_earth_2012_fieldlines_pfss.asset
> +    GUI = {
Indentation error with the GUI table here

2022-04-26 11:32 UTC, alexanderbock commented on modules/fieldlinessequence/rendering/renderablefieldlinessequence.cpp
> +            //_colorTablePaths[_colorQuantity] = _colorTablePath;
This comment seems extra?

2022-04-29 11:10 UTC, WeirdRubberDuck commented on data/assets/scene/solarsystem/heliosphere/2012/sun_earth_2012_fieldlines_batsrus.asset
> +-- Specifying transfer functions
Seems like this is data, and not a transfer function? Both of these comments can be removed anyway imo. ot really needed :)

2022-04-29 11:10 UTC, WeirdRubberDuck commented on data/assets/scene/solarsystem/heliosphere/2012/sun_earth_2012_fieldlines_batsrus.asset
> +
remove this extra line?

2022-04-29 13:36 UTC, WeirdRubberDuck requested changes

2022-04-29 13:45 UTC, WeirdRubberDuck commented
I tried adding the assets and can't load any of the synced data resources. Guessing that they might not be uploaded yet?

Makes it difficult to test 😁

2022-04-29 16:58 UTC, GPayne commented
@WeirdRubberDuck Regarding the synced data resources: These files have been uploaded to the Utah data server. But downloads of the large data files seem to fail before completing (I can download them locally). Elon has had trouble with this, and I've replicated the failures by attempting remote downloads via VPN. I am working with our IT dept to solve this.

2022-05-04 14:53 UTC, merged