Issue/1712
OpenSpace/OpenSpace pull request #2589
Opened 2023-04-10 15:44 UTC by micahnyc

Added dwarf planet assets
Added dwarf planets to default_full
Changed color of ceres trail to match others.

2023-04-10 19:12 UTC, alexanderbock requested changes

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/haumea/label.asset
> +    MinMaxSize = { 1, 100 },
-> `{ 1.0, 100.0 }`

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/haumea/planet.asset
> +      RotationAxis = {0, 0, 1},
-> `{ 0.0, 0.0, 1.0 }`

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/haumea/planet.asset
> +      RotationRate = 1/(3.9154*60*60)
-> `1.0`

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/haumea/trail.asset
> +    Enabled = asset.Enabled,
-> `asset.enabled`

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/makemake/label.asset
> +    Enabled = asset.Enabled,
-> `asset.enabled`

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/makemake/label.asset
> +    MinMaxSize = { 1, 100 },
-> `{ 1.0, 100.0 }`

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/makemake/makemake.asset
> +local trail = asset.require("./trail").Trail
Same as above

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/makemake/planet.asset
> +  Identifier = "dwarf_planet_models",
Same here;  `dwarf_planet_models_makemake` or `makemake_planet_models`

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/makemake/planet.asset
> +      RotationAxis = {0, 0, 1},
-> `{ 0.0, 0.0, 1.0 }`

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/makemake/planet.asset
> +      RotationRate = 1/(10.273*60*60)
-> `1.0`

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/orcus/label.asset
> +    Enabled = asset.Enabled,
-> `asset.enabled`

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/orcus/label.asset
> +    MinMaxSize = { 1, 100 },
-> `{ 1.0, 100.0 }`

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/orcus/orcus.asset
> +local trail = asset.require("./trail").Trail
Same discussion as above

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/orcus/planet.asset
> +      RotationAxis = {0, 0, 1},
-> `{ 0.0, 0.0, 1.0 }`

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/quaoar/planet.asset
> +      RotationRate = 1/(8.84*60*60)
-> `1.0`

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/quaoar/quaoar.asset
> +local trail = asset.require("./trail").Trail
Same discussion as above

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/sedna/label.asset
> +    Enabled = asset.Enabled,
-> `asset.enabled`

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/sedna/label.asset
> +    MinMaxSize = { 1, 100 },
-> `{ 1.0, 100.0 }`

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/sedna/planet.asset
> +      RotationAxis = {0, 0, 1},
-> `{ 0.0, 0.0, 1.0 }`

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/sedna/planet.asset
> +      RotationRate = 1/(10.273*60*60)
-> `1.0`

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/sedna/planet.asset
> +    Radii = { 995.0E3, 1060.0E3, 1025.0E3 },
Easier to read: `{ 995000, 1060000, 1025000 }`

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/sedna/sedna.asset
> +local trail = asset.require("./trail").Trail
Same discussion as above

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/sedna/trail.asset
> +    Enabled = asset.Enabled,
-> `asset.enabled`

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/vesta/label.asset
> +    Enabled = asset.Enabled,
-> `asset.enabled`

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/vesta/label.asset
> +    MinMaxSize = { 1, 100 },
-> `{ 1.0, 100.0 }`

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/vesta/planet.asset
> +      RotationAxis = {0, 0, 1},
-> `{ 0.0, 0.0, 1.0 }`

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/vesta/planet.asset
> +      RotationRate = 1/(5.34212766*60*60)
-> `1.0`

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/vesta/planet.asset
> +    AmbientIntensity = 0.0,
Why do these need special handling, but the other models do not?

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/vesta/trail.asset
> +    Enabled = asset.Enabled,
-> `asset.enabled`

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/vesta/vesta.asset
> +local trail = asset.require("./trail").Trail
Same discussion as for the other objects

2023-04-10 19:12 UTC, alexanderbock commented on data/assets/scene/solarsystem/dwarf_planets/vesta/vesta.asset
> +  Name = "Haumea (Keplerian)",
Copy and paste error

2023-04-11 01:31 UTC, micahnyc commented
[hamuea_model.zip](https://github.com/OpenSpace/OpenSpace/files/11195242/hamuea_model.zip)
[makemake_model.zip](https://github.com/OpenSpace/OpenSpace/files/11195244/makemake_model.zip)
[eris_model.zip](https://github.com/OpenSpace/OpenSpace/files/11195245/eris_model.zip)

2023-04-13 12:44 UTC, alexanderbock commented
Seems odd that the labels for the dwarf planets are enabled where as the other planets are not in the default_full.  So we should disable those labels as well
![image](https://user-images.githubusercontent.com/4921724/231762171-af21e0dc-7f42-49a2-8461-63a3de2e1f92.png)

2023-04-14 17:02 UTC, merged