Video module
OpenSpace/OpenSpace pull request #2608
Opened 2023-04-13 12:29 UTC by Roxeena

Adds a new module that can decode videos (using libmpv) and has a few renderables that can have a video attached to them, globes, spheres, planes, screenspace planes, etc. There is an example asset in the examples folder that you can use to test it out. 

There is a known render bug that will be fixed later. If you have a video plane or a video sphere and place it in front of an atmosphere, the atmosphere is still rendered on top when it shouldn't. This is an issue that we already had with our other planes and spheres too.

@ylvaselling do you have anything you want to add to this description?

2023-04-13 13:18 UTC, alexanderbock requested changes

2023-04-13 13:18 UTC, alexanderbock commented on modules/video/src/videoplayer.cpp
> +        "be either a file path or a url to a youtube video."
I don't think it can be a YouTube video anymore?

2023-04-13 13:18 UTC, alexanderbock commented on modules/video/src/videoplayer.cpp
> +}
These functions can be defined in the anonymous namespace above which makes them less visible to the outside

2023-04-13 13:18 UTC, alexanderbock commented on modules/video/src/videoplayer.cpp
> +{
This `{` can be on the previous line

2023-04-13 13:18 UTC, alexanderbock commented on modules/video/src/videoplayer.cpp
> +            throw ghoul::MissingCaseException();
Everything here would be indented one level higher

2023-04-13 13:18 UTC, alexanderbock commented on modules/video/src/videoplayer.cpp
> +                " end time");
The `);` goes on the next line

2023-04-13 13:18 UTC, alexanderbock commented on modules/video/src/videoplayer.cpp
> +    mpv_set_property_string(_mpvHandle, "msg-level", "all=v");
Can use the `setPropertyStringMpv` function here as well?

2023-04-13 13:18 UTC, alexanderbock commented on modules/video/src/videoplayer.cpp
> +            _isPaused = *videoIsPaused == 1;
maybe `_isPaused = (*videoIsPaused == 1);`  to make it more obvious

2023-04-13 13:18 UTC, alexanderbock commented on modules/video/src/videoplayer.cpp
> +
Extra empty line

2023-04-13 13:18 UTC, alexanderbock commented on modules/video/src/videoplayer.cpp
> +            break;
No need for the `break` here, since the `throw` in the line above will yeet us out of this function anyway

2023-04-13 13:18 UTC, alexanderbock commented on modules/video/src/videoplayer.cpp
> +VideoPlayer::~VideoPlayer() {}
I'd put the destructor just after the constructor since they belong logically together

2023-04-13 13:18 UTC, alexanderbock commented on modules/video/src/videotileprovider.cpp
> + * Copyright (c) 2014-2022                                                               *
-> 2023

2023-04-13 13:18 UTC, alexanderbock commented on modules/video/src/videotileprovider.cpp
> +} // namespace openspace::video
-> `// namespace openspace`

2023-04-13 13:18 UTC, alexanderbock commented on modules/video/video.asset
> +  Video = "C:/Users/ylvaselling/Documents/Work/Testmovies/result.mp4",
Same as above;  if we need another test video, you can send it to me;  otherwise we can reuse one of the other test videos

2023-04-13 13:18 UTC, alexanderbock commented on modules/video/video.asset
> +  Video = "C:/Users/ylvaselling/Documents/Work/Testmovies/result.mp4",
File should be moved to data/assets/examples either way if you want to keep it

2023-04-13 13:18 UTC, alexanderbock commented on modules/video/video.asset
> +local layer = {
This asset should require the earth asset since we depend on it

2023-04-13 13:18 UTC, alexanderbock commented on modules/video/video.asset
> +  License = "NASA"
Meta information needs to be updated

2023-04-14 19:33 UTC, ylvaselling commented on modules/globebrowsing/CMakeLists.txt
> +if(WIN32)
My VSCode edits Cmakelists files just when I open them :'(

2023-04-14 20:09 UTC, ylvaselling commented on modules/video/src/videoplayer.cpp
> +                LWARNING("Detected fps was 0. Falling back on 24 fps");
Fps can be negative?

2023-04-14 22:28 UTC, merged