increase timeout for gdal http and updated url for loading gibs
OpenSpace/OpenSpace pull request #3015
Opened 2024-01-31 19:04 UTC by micahnyc

a value of 10 worked for me but I thought to make it 15 for EU users....

2024-01-31 19:05 UTC, micahnyc commented
fixes #1250

2024-02-05 15:51 UTC, micahnyc commented
want to check if this is affecting the loading of the tiles

2024-02-06 14:53 UTC, alexanderbock commented on modules/globebrowsing/globebrowsingmodule.cpp
> +#include <cpl_conv.h>
```suggestion
#include <cpl_conv.h>
#include <cpl_string.h>
```

2024-02-06 14:55 UTC, alexanderbock requested changes

2024-02-06 14:55 UTC, alexanderbock commented on modules/globebrowsing/globebrowsingmodule.cpp
> +        CPLSetConfigOption("GDAL_HTTP_TIMEOUT", "15");
Would be better to move this to the GDALWrapper class where we already have:

`    CPLSetConfigOption("GDAL_HTTP_TIMEOUT", "3"); // 3 seconds`

2024-02-14 23:40 UTC, alexanderbock commented
Can you squash-merge the commits as the current commit messages are not standard (not starting with a capital letter, for example)

2024-02-27 15:31 UTC, merged