NavigationState handling
OpenSpace/OpenSpace pull request #3023
Opened 2024-02-12 02:43 UTC by alexanderbock

Change the navigation state format from Lua to JSON (applies to `openspace.navigation.saveNavigationState` and `openspace.navigation.loadNavigationState`. Before, the `yaw` and `pitch` values were ignored if the `up` vector was not specified. Now, these three values are loaded independently.

Add the ability to set the navigation state in the profile editor based on the new JSON format.

2024-02-12 02:43 UTC, alexanderbock commented
Closes #2117 when merged

2024-02-19 09:54 UTC, WeirdRubberDuck commented on src/navigation/navigationhandler.cpp
> +        (std::istreambuf_iterator<char>(f)),
```suggestion
        std::istreambuf_iterator<char>(f),
```
?

2024-02-19 10:11 UTC, WeirdRubberDuck requested changes
Noticed that it is still not saved using a file extension.  Should we?  

Either json, or maybe our custom one 

Also, note to us: this is a highly breaking change and should be included in the list of breaking changes that I have started adding to the docs in this PR: 

https://github.com/OpenSpace/OpenSpace-Docs/pull/11  
(still waiting for someone to read it)

2024-02-19 10:11 UTC, WeirdRubberDuck commented on src/navigation/navigationstate.cpp
> +        referenceFrame = it->get<std::string>();
This should be set to the anchor node if the reference frame was not specified

2024-02-19 10:11 UTC, WeirdRubberDuck commented on src/navigation/navigationstate.cpp
> +        referenceFrame = it->get<std::string>();
Currently, loading a navigation stat ethat looks like this leads to an error:
```
{
  "anchor": "Earth",
  "position": {
    "x": 13514805.101321544,
    "y": 5454659.039307959,
    "z": -18279333.341204002
  },
  "up": {
    "x": 0.8035739201794957,
    "y": 0.0035944893626913277,
    "z": 0.59519411493527
  }
}
```

![image](https://github.com/OpenSpace/OpenSpace/assets/8808894/d1c26b97-488f-4854-939a-c2581e7c3f01)

2024-02-24 23:56 UTC, alexanderbock commented
If the path provided to the `saveNavigationState` doesn't have an extension, a `.navstate` one is now added. If the user _did_ provide a different extension, that one is used instead

2024-02-25 00:09 UTC, merged