UI updates
OpenSpace/OpenSpace pull request #3358
Opened 2024-07-24 11:05 UTC by ylvaselling

To be used with this PR: https://github.com/OpenSpace/OpenSpace-WebGuiFrontend/pull/194

This PR will mirror (hopefully) all updates to the property tree in the UI, including:
* All property owner removals and additions during runtime
* All property removals and additions during runtime
* Globebrowsing layer reorderings

Changes made:
* Removed all events for removing and adding SceneGraphNodes, ScreenSpaceRenderables and Layers
* Instead created two new events: PropertyTreeUpdated and PropertyTreePruned
* These events are published in the PropertyOwner functions addProperty, addPropertySubowner, removeProperty, and removePropertySubowner, to ensure that all changes in the property tree are reflected in the UI
* The URI of the Property or PropertyOwner is validated before the event is published
* Necessary adjustments to the UI code

Testing is encouraged:) For example doing this during runtime:
* Adding and removing assets
* Removing and adding properties with scripting 
* Reorder, add, and remove layers
* Modify properties such as OptionProperty
* etc

Notes:
* There are some bugs in the layer reordering and removal of layers from the UI that are not related to the changes made in this PR
* I removed some code in the UI in the DragDropLayerList. I watched the tutorial linked and in that he didn't use the refs that we had. The motivation seemed to be to prevent unnecessary re-renders but that does not seem to be a problem. The refs did however make it difficult to sync with Redux

Closes #3342, #3339, #3331, #3263, #1929

2024-07-29 09:09 UTC, WeirdRubberDuck requested changes
Tried it out and this issue is still a problem: 
https://github.com/OpenSpace/OpenSpace/issues/3342 

The event maybe have to be triggered when an option is added to the options property as well? Or can it be handled somewhere higher up to be more generic?

Also, we should discuss whether we want to keep something like the "scene graph node added" event around, for users to tie actions to 

I also have some requests on updating the comments in connection to where the events are being triggered. Currently it is a bit hard to read, and understand why the URI needs to be validated (and why the event does not have to be triggered when they are invalid). See comments in code and let me know if something is unclear.

2024-07-29 09:09 UTC, WeirdRubberDuck commented on src/properties/propertyowner.cpp
> +            if (!uriParent.empty()) {
Also, maybe include information about what is being updated. Takes a few seconds to interpret the code and see if we are updating a property or propertyowner. 

Alternatively, what about creating helper functions for updating propertyowner and properties? Thar could enhance readability quite a bit. E.g. here, moving all the code to a function: 
```cpp
void publishEventPropertyUpdated(std::string_view parentUri, std::string_view propertyId) {
    // Validate URI, <TODO: WHY??>
    if (!parentUri.empty()) {
        std::string id = std::format("{}.{}", parentUri, propertyId);
        global::eventEngine->publishEvent<events::EventPropertyTreeUpdated>(id);
    }
}
```

```cpp
void publishEventPropertyOwnerUpdated(std::string_view ownerUri) {
    // Validate URI, <TODO: WHY??>
    if (!ownerUri.empty()) {
        global::eventEngine->publishEvent<events::EventPropertyTreeUpdated>(ownerUri);
    }
}
```

2024-07-29 13:24 UTC, WeirdRubberDuck commented on include/openspace/events/event.h
> + * This event is created a property owner or property has been added or has changed.
Maybe here is where that additional detail should be included

2024-07-30 12:37 UTC, alexanderbock approved these changes
Is there a better name for "Pruned"?  It's clear what it does, so I'm not _really_ against it, but wondering if there is a better "technical" term for it 🤔

2024-07-30 14:33 UTC, WeirdRubberDuck commented
> Not sure if this is an issue with the branch since I got it on #3363 as well, but I get
> 
> ```
> [0730/143238.867:INFO:CONSOLE(75994)] "Warning: validateDOMNesting(...): %s cannot appear as a descendant of <%s>.%s <button> button
>     at button
>     at http://127.0.0.1:4690/frontend/static/bundle.js:36669:81
>     at Checkbox (http://127.0.0.1:4690/frontend/static/bundle.js:36746:22)
>     at span
>     at div
>     at div
>     at http://127.0.0.1:4690/frontend/static/bundle.js:38757:99
>     at button
>     at http://127.0.0.1:4690/frontend/static/bundle.js:36669:81
>     at PropertyOwnerHeader (http://127.0.0.1:4690/frontend/static/bundle.js:32278:23)
>     at div
>     at ToggleContent (http://127.0.0.1:4690/frontend/static/bundle.js:39096:26)
>     at PropertyOwner (http://127.0.0.1:4690/frontend/static/bundle.js:32098:19)
>     at ContextSection (http://127.0.0.1:4690/frontend/static/bundle.js:31090:34)
>     at div
>     at ScrollOverlay (http://127.0.0.1:4690/frontend/static/bundle.js:38806:24)
>     at FilterListFavorites (http://127.0.0.1:4690/frontend/static/bundle.js:36317:25)
>     at div
>     at FilterList (http://127.0.0.1:4690/frontend/static/bundle.js:36423:23)
>     at div
>     at section
>     at Pane (http://127.0.0.1:4690/frontend/static/bundle.js:31362:23)
>     at ScenePane (http://127.0.0.1:4690/frontend/static/bundle.js:32992:28)
>     at section
>     at div
>     at Resizable (http://127.0.0.1:4690/frontend/static/bundle.js:67573:28)
>     at Sidebar (http://127.0.0.1:4690/frontend/static/bundle.js:33422:27)
>     at section
>     at RefsProvider (http://127.0.0.1:4690/frontend/static/bundle.js:29368:51)
>     at div
>     at OnScreenGui (http://127.0.0.1:4690/frontend/static/bundle.js:40738:26)
>     at RenderedRoute (http://127.0.0.1:4690/frontend/static/bundle.js:138226:5)
>     at Routes (http://127.0.0.1:4690/frontend/static/bundle.js:138847:5)
>     at Router (http://127.0.0.1:4690/frontend/static/bundle.js:138785:15)
>     at HashRouter (http://127.0.0.1:4690/frontend/static/bundle.js:136886:5)
>     at App
>     at Provider (http://127.0.0.1:4690/frontend/static/bundle.js:131045:20)", source: http://127.0.0.1:4690/frontend/static/bundle.js (75994)
> ```
> 
> as an entry in the OpenSpace console

This is unrelated to this PR and has been fixed as part of this other PR: https://github.com/OpenSpace/OpenSpace-WebGuiFrontend/pull/191

2024-08-02 08:38 UTC, ylvaselling commented
> Tried it out and this issue is still a problem: #3342
> 
> The event maybe have to be triggered when an option is added to the options property as well? Or can it be handled somewhere higher up to be more generic?
> 
> Also, we should discuss whether we want to keep something like the "scene graph node added" event around, for users to tie actions to
> 
> I also have some requests on updating the comments in connection to where the events are being triggered. Currently it is a bit hard to read, and understand why the URI needs to be validated (and why the event does not have to be triggered when they are invalid). See comments in code and let me know if something is unclear.

Good spotting! Yeah I think that one is hard to have generic. We could have a function in the Property base class called something like "PropertyModified" where the event is published. Then in the future, when someone modifies that property, they can just call `Property::PropertyModified`. (with better naming).

2024-08-02 12:31 UTC, ylvaselling commented
Looked into #3342, it seems it is unrelated to this issue. There is a `notifyChangeListeners` function that seems to use the topics to send the changes to the UI. Emma and I tested putting it in the `addOption` function, but it throws an out of range error. I'll put this information in that issue too.

2024-08-02 13:37 UTC, alexanderbock commented
> > Is there a better name for "Pruned"? It's clear what it does, so I'm not _really_ against it, but wondering if there is a better "technical" term for it 🤔
> 
> If you have a better suggestion, please let me know 😄

Unfortunately not :(

2024-08-02 14:30 UTC, merged